import time
import os
hp = 100

def Emily():
    os.system('clear')
print('Let the adventure begin!')
time.sleep(1)
print('Once upon a time.')
time.sleep(1)
print('There lived a young girl named Emily.')
time.sleep(1)
print("She lived in the city of Valeria.")
time.sleep(1)
print('Now, Emily wasn\'t any ordinary girl.')
time.sleep(1)
print('She was gifted with extraordinary intelligence, agility, and the power to control ice.')
time.sleep(1)
print('One day')
time.sleep(1)
print('Her rich mother told her that now she was 18 years old')
time.sleep(1)
print('She had to explore the world and use her skills to help others.')
time.sleep(1)
print('But here\'s the plot twist')
time.sleep(1)
print('She wanted to embark on a journey to discover hidden secrets.')
time.sleep(1)
print('But little did she know what challenges she would face and what adventures she would have to overcome to achieve her goals.')
time.sleep(1)
print('Otherwise...')
time.sleep(5)
os.system('clear')
coin_count = 80
print("You set out for an adventure with 80 coins")
time.sleep(1)