import os
import time
hp = 100

def Jack():
    os.system('clear')
print('Let the adventure begin! ')
import time
time.sleep(1)
print('There lived a young boy named Jack.')
time.sleep(1)
print('Now, Jack wasn\'t any ordinary boy. ')
time.sleep(1)
print('He was gifted the power to have crazy powers such as lightning summoning and fire control')
time.sleep(1)
print('One day')
time.sleep(1)
print('His mother told him that now he was 16 years old')
time.sleep(1)
print('He had to feed himself and make a living out of himself.')
time.sleep(1)
print('But here\'s the plot twist')
time.sleep(1)
print('He wanted to set out into the unknown.')
time.sleep(1)
print(
	'But little did he know what he would face and what adventures he would have to overcome to save his life')
time.sleep(1)
print('Otherwise...')
time.sleep(5)
os.system("clear")
print("You set out for an adventure with 50 coins")
coin_count = 50
time.sleep(1)
print("The day is starting to end, but you don't find anywhere to rest")
time.sleep(1)
print("All of a sudden, you see a motel at the end of the forest you were walking in.")
time.sleep(1)
print("You think whether you should go or not.")
time.sleep(1)
optionA = input("Do you want to go or not? Pick yes or no. ")
time.sleep(1)
if optionA == "yes":
	os.system('clear')
	print("You walk into the motel.")
	time.sleep(1)
	print("You go up to the front desk lady.")
	time.sleep(1)
	print("She asks if you want a room for 2 coins")
	hotel_room_request = input("Do you take it? ")
	if hotel_room_request == "yes":
		coin_count = coin_count - 2
		time.sleep(1)
		os.system('clear')
		time.sleep(1)
		print("You now have " + str(coin_count) + " coins left")
		time.sleep(1)
		print("The lady takes you to your room.")
		time.sleep(1)
		print("You go to your bed and you go to sleep.")
		time.sleep(1)
		os.system('clear')
		time.sleep(10)
		print("You wake up.")
		time.sleep(1)
		print("You leave the motel.")
		time.sleep(1)
		print("You step back out into the wilderness.")
		time.sleep(1)
		os.system('clear')
		print("You continue your journey")
		time.sleep(1)
		print("As you walk along the footpath, you see a city emerge.The city of Valeria")
		time.sleep(1)
		os.system('clear')
		time.sleep(1)
		print("A new chapter begins")
		time.sleep(2)
		os.system('clear')
		time.sleep(1)
		print("The Kingdom of Valeria is known to have a notorious king.")
		time.sleep(1)
		os.system('clear')
		time.sleep(1)
		print("Rumors say that anyone who enters Valeria without the king being notified, he will send assassins to attack you at night.")
		time.sleep(2)
		os.system('clear')
		time.sleep(2)
		print("You walk forward into the road which leads to the entrance of the Kingdom of Valeria")
		time.sleep(1)
		print("Your hunger is killing you.")
		time.sleep(2)
		print("You see 2 guards stationed at a gate.")
		time.sleep(1)
		print("You decide whether to attack them or find a different way in.")
		time.sleep(1)
		print("You decide to throw some natural sedating scents that you found when you were walking in the jungle to make them fall asleep and then quickly enter the kingdom without anyone noticing.")
		time.sleep(2)
		print("You enter the kingdom without worrying about anything.")
		time.sleep(1)
		os.system('clear')
		time.sleep(1)
		print("A new chapter begins.")
		time.sleep(1)
		os.system('clear')
		time.sleep(1)
		print("You enter the kingdom.")
		time.sleep(1)
		print("The city is bustling with people.")
		time.sleep(1)
		print("As you walk through the city, you went to a restaurant to eat because of how hungry you were.")
		time.sleep(1)
		print("You order your food. The man that was serving you said your total price was 20 coins")
		time.sleep(2)
		food = input("Do you want to accept or not? ")
		if food == "yes" or "Yes" or "Y" or "y":
			print("ok")
		elif food == "no" or "No" or "N" or "n":
			time.sleep(1)
			print("You exit the restaurant.")
			time.sleep(1)
			print("You start getting dizzy")
			time.sleep(2)
			print("Your limbs start turning numb.")
			time.sleep(3)
			print("You faint in an alley way.")
			time.sleep(4)
			print("Your limbs start turning blue!")
			time.sleep(1)
			print("You died!")
			print("Restart the console to play again.")
	elif hotel_room_request == "no":
		time.sleep(1)
		print("You ask if there are cheaper rooms.")
		time.sleep(1)
		print("The lady says no.")
		time.sleep(1)
		print("You get out of the hotel.")
		time.sleep(1)
		print("You sense danger in the dark.")
		time.sleep(1)
		print("A monster jumps out.")
		time.sleep(1)
		attack1 = input("Do you attack, defend, or dodge? ")
		time.sleep(1)
		if attack1 == "attack":
			time.sleep(1)
			print("You attacked the monster. The monster took 40 damage")
			time.sleep(1)
			print("The monster recoils.")
			time.sleep(1)
			attack2 = input("Do you attack, defend, or dodge? ")
			time.sleep(1)
			if attack2 == "attack":
				print("You attacked the monster. Ooof!! Critical hit!! The monster took 60 damage.")
				time.sleep(1)
				print("You killed the monster.")
			elif attack2 == "defend":
				print("The monster attacked you. You defended yourself and took 5 damage.")
				hp = hp - 5
				time.sleep(1)
				print("You have " + str(hp) + " health left.")
				time.sleep(1)
				attack4 = input("Do you attack, defend, or dodge? ")
				if attack4 == "attack":
					print("You attacked the monster. The monster took 40 damage.")
					attack5 = input("Do you attack, defend, or dodge? ")
					if attack5 == "attack":
						print("Ooof!! Critical hit!! The monster took 60 damage. ")
						time.sleep(1)
						print("You killed the monster.")
				elif attack4 == "defend":
					print("You defended yourself against the monster. However, you still took 5 damage.")
					hp = hp - 5
					
				elif attack4 == "dodge":
					print("The monster attacked you. You dodged. You stunned yourself.")
			elif attack2 == "dodge":
				print("The monster attacked you but you dodged. You stunned yourself.")
		elif attack1 == "defend":
			time.sleep(1)
			print("The monster attacked you. You defended yourself and took 5 damage")
			time.sleep(1)
			attack3 = input("Do you attack, defend, or dodge?")
			if attack3 == "attack":
				time.sleep(1)
				print("You attacked the monster. Ooof!! Critical hit!! The monster took 60 damage")
			elif attack3 == "defend":
				print("The monster attacked you. You defended yourself and took 5 damage. ")
				hp = hp - 5
			elif attack3 == "dodge":
				print("The monster attacked you. You defended yourself and took 5 damage")
		elif attack1 == "dodge":
			time.sleep(1)
			print("The monster attacked you but you dodged. You stunned yourself. ")
			#attack = input("Do you attack or defend?")
elif optionA == "no":
	print('ok')
